apiVersion: apps/v1
kind: Deployment
metadata:
  name: suricata-deployment
spec:
  selector:
    matchLabels:
      app: suricata
  replicas: 1
  template:
    metadata:
      labels:
        app: suricata
    spec:
      containers:
      - name: suricata-container
        image: jasonish/suricata:latest
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_NICE
        command: ["suricata", "-i", "<interface>"]
        # Replace <interface> with the name of the interface you want to use.

